# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               clojuristas
tagline:             (get clojure)
description:         where we come for clojure
url:                 http://cjdev.github.io/clojuristas/
baseurl:             '/clojuristas'
paginate:            5

# About/contact
author:
  name:              cj clojuristas
  url:               https://cjdev.github.com/clojuristas/
  email:             cjdev@cj.com

# Custom vars
version:             1.0.0
